[package]
name = "camera_node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "camera_node"
path = "src/main.rs"

[dependencies]
dora-node-api = "0.3.13"
opencv = { version = "0.97.2", features = ["clang-runtime"] }
arrow = "54.3.1"
